sever:
  port: 8081

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  timeout: 600000
  jedis:
    pool:
      max-idle: 500
      min-idle: 50
      max-total: 2000
      max-wait: 1000

nomad:
  host: http://127.0.0.1:4646
  dataCenters:
    dc1
  dockerImage: test_python:0.5

spring:
  influx:
    url: http://101.35.96.159:8086
    database: stress
    user: user
    password: varqiao

clone:
  path: /Users/user/test/pull

